# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "make-vertx-redisques-build-pass-on-github-actions" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build_maven:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [ 4 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Build with Maven
        run: mvn install -Dmaven.javadoc.skip=true -B -V

  release:
    needs: build_maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}

      - if: ${{ env.CI_DEPLOY_USERNAME != '' }}
        run: echo 'This step will only run if the secret has a value set.'

      - name: Run release
        run: |
          git config --global user.email "swisspush@post.ch"
          git config --global user.name "Github-CI"
          
          git config credential.helper "store --file=.git/credentials"
          echo "https://${GH_TOKEN}:@github.com" > .git/credentials
          
          chmod +x .github/maybe-release-github.sh
          
          curl -s get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install groovy 3.0.8
          
          .github/maybe-release-github.sh

  after_release:
    needs: [ release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run after release
        run: bash <(curl -s https://codecov.io/bash)