name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '11'
          server-id: sonatype-nexus-snapshots # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: CI_DEPLOY_USERNAME # env variable for username in deploy
          server-password: CI_DEPLOY_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: CI_PGP_PASSWORD # env variable for GPG private key passphrase

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 4

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          CI_PGP_PASSWORD: ${{ secrets.CI_PGP_PASSWORD }}